"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.replaceRecords = exports.replaceRecord = exports.updateRecords = exports.updateRecord = exports.getRecords = exports.getRecord = void 0;
var requests_1 = require("./requests");
Object.defineProperty(exports, "getRecord", { enumerable: true, get: function () { return requests_1.getRecord; } });
Object.defineProperty(exports, "getRecords", { enumerable: true, get: function () { return requests_1.getRecords; } });
Object.defineProperty(exports, "updateRecord", { enumerable: true, get: function () { return requests_1.updateRecord; } });
Object.defineProperty(exports, "updateRecords", { enumerable: true, get: function () { return requests_1.updateRecords; } });
Object.defineProperty(exports, "replaceRecord", { enumerable: true, get: function () { return requests_1.replaceRecord; } });
Object.defineProperty(exports, "replaceRecords", { enumerable: true, get: function () { return requests_1.replaceRecords; } });
