import type {
  CreateRequiredMode,
  NormalizedBase,
  NormalizedField,
  SchemaMode,
} from './types.js';
import { quotePropertyKey } from './identifiers.js';

function isPrimaryCreateField(
  field: NormalizedField,
  primaryFieldId: string,
  createRequiredMode: CreateRequiredMode
): boolean {
  return (
    createRequiredMode === 'primaryField' &&
    field.id === primaryFieldId &&
    Boolean(field.createType)
  );
}

function getFieldTypeForKind(
  field: NormalizedField,
  kind: 'read' | 'create' | 'update'
): string | undefined {
  if (kind === 'read') return field.readType;
  if (kind === 'create') return field.createType;
  return field.updateType;
}

function groupFieldsByPropertyKey(
  fields: NormalizedField[],
  kind: 'read' | 'create' | 'update'
): Array<{ key: string; fields: NormalizedField[] }> {
  const groups = new Map<string, NormalizedField[]>();

  fields.forEach((field) => {
    const type = getFieldTypeForKind(field, kind);
    if (!type) return;

    const existing = groups.get(field.tsKey);
    if (existing) {
      existing.push(field);
      return;
    }

    groups.set(field.tsKey, [field]);
  });

  return [...groups.entries()].map(([key, groupedFields]) => ({
    key,
    fields: groupedFields,
  }));
}

function unionTypes(types: string[]): string {
  const distinctTypes = [...new Set(types)];
  return distinctTypes.join(' | ');
}

function emitInterface({
  name,
  fields,
  kind,
  primaryFieldId,
  createRequiredMode,
}: {
  name: string;
  fields: NormalizedField[];
  kind: 'read' | 'create' | 'update';
  primaryFieldId: string;
  createRequiredMode: CreateRequiredMode;
}): string {
  const groupedFields = groupFieldsByPropertyKey(fields, kind);

  const lines = groupedFields.map(({ key, fields: grouped }) => {
    const propertyTypes = grouped
      .map((field) => getFieldTypeForKind(field, kind))
      .filter((type): type is string => Boolean(type));

    const propertyType = unionTypes(propertyTypes);
    const isRequired =
      kind === 'create' &&
      grouped.some((field) =>
        isPrimaryCreateField(field, primaryFieldId, createRequiredMode)
      );

    return `  ${quotePropertyKey(key)}${isRequired ? '' : '?'}: ${propertyType};`;
  });

  if (!lines.length) {
    return `export interface ${name} {}`;
  }

  return [`export interface ${name} {`, ...lines, `}`].join('\n');
}

function emitEnumAliases(table: NormalizedBase['tables'][number]): string[] {
  return table.fields
    .filter((field) => Boolean(field.enumTypeAlias))
    .map((field) => `export type ${field.tsTypeName} = ${field.enumTypeAlias};`);
}

function emitTableIds(normalizedBase: NormalizedBase): string {
  const lines = normalizedBase.tables.map(
    (table) => `  ${table.tsConstKey}: ${JSON.stringify(table.id)},`
  );

  return ['export const tables = {', ...lines, '} as const;'].join('\n');
}

function emitFieldIds(normalizedBase: NormalizedBase): string {
  const lines = normalizedBase.tables.map((table) => {
    const fieldLines = table.fields.map(
      (field) => `    ${field.tsConstKey}: ${JSON.stringify(field.id)},`
    );

    return [`  ${table.tsConstKey}: {`, ...fieldLines, '  },'].join('\n');
  });

  return ['export const fields = {', ...lines, '} as const;'].join('\n');
}

export function emitTypeScript({
  normalizedBase,
  includeTableIds,
  includeFieldIds,
  schemaMode,
  createRequiredMode,
}: {
  normalizedBase: NormalizedBase;
  includeTableIds: boolean;
  includeFieldIds: boolean;
  schemaMode: SchemaMode;
  createRequiredMode: CreateRequiredMode;
}): string {
  const sections: string[] = [
    '/* eslint-disable */',
    '// Generated by easy-airtable-api. Do not edit manually.',
    "// Generated record-field types assume Airtable's default response mode: cellFormat: 'json' and returnFieldsByFieldId: false.",
    '',
    "import type { AICell, AirtableRecord, Attachment, AttachmentWrite, BarcodeCell, BarcodeWrite, ButtonCell, Collaborator, CollaboratorWrite } from 'easy-airtable-api';",
  ];

  if (includeTableIds) {
    sections.push('', emitTableIds(normalizedBase));
  }

  if (includeFieldIds) {
    sections.push('', emitFieldIds(normalizedBase));
  }

  normalizedBase.tables.forEach((table) => {
    sections.push('');
    sections.push(`// ${table.name} (${table.id})`);

    const enumAliases = emitEnumAliases(table);
    if (enumAliases.length) {
      sections.push(...enumAliases, '');
    }

    if (schemaMode === 'read' || schemaMode === 'full') {
      sections.push(
        emitInterface({
          name: `${table.tsName}RecordFields`,
          fields: table.fields,
          kind: 'read',
          primaryFieldId: table.primaryFieldId,
          createRequiredMode,
        })
      );
      sections.push(
        `export type ${table.tsName}Record = AirtableRecord<${table.tsName}RecordFields>;`
      );
    }

    if (schemaMode === 'write' || schemaMode === 'full') {
      sections.push(
        emitInterface({
          name: `${table.tsName}CreateFields`,
          fields: table.fields,
          kind: 'create',
          primaryFieldId: table.primaryFieldId,
          createRequiredMode,
        })
      );
      sections.push(
        emitInterface({
          name: `${table.tsName}UpdateFields`,
          fields: table.fields,
          kind: 'update',
          primaryFieldId: table.primaryFieldId,
          createRequiredMode,
        })
      );
    }
  });

  return `${sections.join('\n')}\n`;
}
